name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -project kubec-cmd.xcodeproj -scheme 'kubec-cmd' -configuration Release build -derivedDataPath DerivedData | xcpretty
    - name: Run tests
      run: xcodebuild -project kubec-cmd.xcodeproj -scheme 'kubec-cmd' -configuration Debug test | xcpretty
    - name: Archive binary
      run: |
        cp DerivedData/Build/Products/Release/kubec-cmd/kubec-cmd.bin
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: kubec-cmd-binary
        path: kubec-cmd.bin
